-keep class org.apache.poi.** { *; }
-keep class com.tom_roush.pdfbox.** { *; }
-dontwarn org.apache.**
-dontwarn javax.**
-dontwarn org.bouncycastle.**
-dontwarn org.openxmlformats.**
-dontwarn com.gemalto.**
-dontwarn org.w3c.**
-dontwarn org.slf4j.**
-dontwarn com.sun.**
-dontwarn org.etsi.**
-dontwarn org.osgi.**
-dontwarn com.graphbuilder.**
-dontwarn com.zaxxer.**
-dontwarn org.checkerframework.**
-dontwarn com.google.errorprone.**
-dontwarn aQute.**
